### ISSUE TITLE
Insert letter

### ISSUE THREAD

**Issue by MarcelVe** [javidan/jkeyboard#1]
Hi, can you help me?
How can i insert a letter by keyboard plugin in the cursor position?
Thank you.

**Comment by javidan** [comment]
Hi
I've updated code. It now should work with cursor position and even with selection.
It will work with modern browsers. I'm not sure for old IE-s.
Thanks

**Comment by MarcelVe** [comment]
Thank you for your attention.
But its not working with IE9, can you help me again?
In IE9 the letter always enter in the first position.
Thank you.

**Comment by javidan** [comment]
Using ie9 is a big problem for humanity:)
I'll try to fix it today. may be use external library for fix.

**Comment by isotestardo** [comment]
Hello javidan, is it possible to modify the code in order to backspace in the cursor posiotion too?
I'm a newbee, I tried to do it by myself, but it seems I'm not able to work it out.

**Comment by digvijayadctex** [comment]
@isotestardo 
Take a look at #7
