### ISSUE TITLE
CSS .active is not valid, need to update to :active

### ISSUE THREAD

**Issue by allchannelson** [javidan/jkeyboard#3]
Self explanatory.  The .active class is not used anywhere in the code, so it really should be the :active pseudo-element, allowing different styling when the button is pressed vs when the button is hovered over.

**Comment by javidan** [comment]
Think you are right, if you have patch I've pleased to accept.

**Comment by allchannelson** [comment]
Created a patch/pull request:
#4

**Comment by javidan** [comment]
@allchannelson thank you, already merged
